version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: wordcloud-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      image: php:7.2-fpm
      container_name: wordcloud-php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
